# Generated by Django 6.0.5 on 2026-05-21 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('current_cycle_used_hours', models.FloatField()),
                ('start_datetime', models.DateTimeField()),
                ('driver_name', models.CharField(blank=True, default='', max_length=255)),
                ('carrier_name', models.CharField(blank=True, default='', max_length=255)),
                ('main_office_address', models.CharField(blank=True, default='', max_length=255)),
                ('vehicle_number', models.CharField(blank=True, default='', max_length=100)),
                ('trailer_number', models.CharField(blank=True, default='', max_length=100)),
                ('shipping_document', models.CharField(blank=True, default='', max_length=100)),
                ('total_miles', models.FloatField(default=0)),
                ('total_driving_hours', models.FloatField(default=0)),
                ('total_on_duty_hours', models.FloatField(default=0)),
                ('route_data', models.JSONField(blank=True, default=dict)),
                ('stops_data', models.JSONField(blank=True, default=list)),
                ('daily_logs', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
